repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: tests
        name: Unit Tests
        description: This hook runs unit tests
        entry: python monstermash_test.py
        language: system
        always_run: true
        pass_filenames: false
